"""Remove WebhookEndpoint.user_id

Revision ID: 1c41b2824616
Revises: 16b19486b490
Create Date: 2025-02-03 11:10:12.714269

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "1c41b2824616"
down_revision = "16b19486b490"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = {t for t in inspector.get_table_names()}

    if "webhook_endpoints" in tables:
        columns = {c["name"] for c in inspector.get_columns("webhook_endpoints")}
        indexes = {i["name"] for i in inspector.get_indexes("webhook_endpoints")}
        fks = {fk["name"] for fk in inspector.get_foreign_keys("webhook_endpoints")}

        if "user_id" in columns:
            op.execute(
                """DELETE FROM webhook_endpoints WHERE user_id IS NOT NULL OR organization_id IS NULL"""
            )

            op.alter_column(
                "webhook_endpoints", "organization_id", existing_type=sa.UUID(), nullable=False
            )

            if "ix_webhook_endpoints_user_id" in indexes:
                op.drop_index("ix_webhook_endpoints_user_id", table_name="webhook_endpoints")

            if "webhook_endpoints_user_id_fkey" in fks:
                op.drop_constraint(
                    "webhook_endpoints_user_id_fkey", "webhook_endpoints", type_="foreignkey"
                )

            op.drop_column("webhook_endpoints", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = {t for t in inspector.get_table_names()}

    if "webhook_endpoints" in tables:
        columns = {c["name"] for c in inspector.get_columns("webhook_endpoints")}
        if "user_id" not in columns:
            op.add_column(
                "webhook_endpoints",
                sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
            )

            op.create_foreign_key(
                "webhook_endpoints_user_id_fkey",
                "webhook_endpoints",
                "users",
                ["user_id"],
                ["id"],
                ondelete="CASCADE",
            )

            op.create_index(
                "ix_webhook_endpoints_user_id", "webhook_endpoints", ["user_id"], unique=False
            )

            op.alter_column(
                "webhook_endpoints", "organization_id", existing_type=sa.UUID(), nullable=True
            )
    # ### end Alembic commands ###
